create database Afficionado_Coffee_Roasters;

use Afficionado_coffee_Roasters;

SELECT COUNT(*)
FROM `coffe_ roasters`;

ALTER TABLE `coffe_ roasters`
RENAME TO coffee_roasters;

select * from coffee_roasters;

ALTER TABLE coffee_roasters
MODIFY transaction_time TIME,
MODIFY store_location VARCHAR(50),
MODIFY unit_price DECIMAL(10,2),
MODIFY product_category VARCHAR(50),
MODIFY product_type VARCHAR(100),
MODIFY product_detail VARCHAR(150),
MODIFY Revenue DECIMAL(10,2),
MODIFY Hours TINYINT;

ALTER TABLE coffee_roasters
MODIFY `Time Bucket` VARCHAR(20),
MODIFY `Day Part Number` TINYINT;

# QUESTIONS:-

#1 wasq that return total revenue generated by all stores
select store_location,sum(revenue) as tr
from coffee_roasters group by 1;

#2 wasq that return total number of transactions
select count(transaction_id) as tn from coffee_roasters;

#3 wasq that return total quantity sold across all stores
select store_location,sum(transaction_qty) as tq
from coffee_roasters group by 1;

#4 wasq that return store-wise total revenue
select store_location,sum(revenue) as tr
from coffee_roasters group by 1;

#5 wasq that return store-wise total transaction count
select store_location,count(transaction_id) ttc
from coffee_roasters group by 1;

#6 wasq that return top 5 stores with highest revenue
select store_location,sum(revenue) as rev
from coffee_roasters group by 1 order by 
rev desc limit 5;

#7 wasq that return bottom 5 stores with lowest revenue
select store_location,sum(revenue) as rev
from coffee_roasters group by 1 order by 
rev asc limit 5;

#8 wasq that return product category-wise total revenue
select product_category,sum(revenue) as tr
from coffee_roasters group by 1;

#9 wasq that return product type-wise total revenue
select product_type,sum(revenue) as tr
from coffee_roasters group by 1;

#10 wasq that return top 10 products with highest revenue
select product_detail,sum(revenue) as r from coffee_roasters
group by 1 order by r desc limit 10;

#11 wasq that return top 10 products with highest transaction count
select product_detail,count(transaction_qty) tc
from coffee_roasters group by 1 order by tc desc limit 10;

#12 wasq that return hourly transaction count across all stores
select store_location,Hours,count(transaction_time) as tm
from coffee_roasters group by 1,2;

#13 wasq that return hourly revenue distribution
select hours,revenue from coffee_roasters;

#14 wasq that return peak transaction hour
select transaction_time from coffee_roasters
order by transaction_time;

#15 wasq that return peak revenue hour
select transaction_time,revenue from coffee_roasters
order by revenue desc;

#16 wasq that return time bucket-wise total revenue
select time_bucket,sum(revenue) as tr
from coffee_roasters group by 1;

#17 wasq that return time bucket-wise transaction count
select time_bucket,count(transaction_id) as tc
from coffee_roasters group by 1;

#18 wasq that return highest revenue generating time bucket
select time_bucket,sum(revenue) as hr from coffee_roasters
group by 1 order by hr desc;

#19 wasq that return store-wise hourly revenue
select store_location,hours,sum(revenue) as r
from coffee_roasters group by 1,2;

#20 wasq that return store-wise hourly transaction count
select store_location,hours,sum(transaction_id) as tc
from coffee_roasters group by 1,2;

#21 wasq that return store-wise peak transaction hour using window function
with cte as
(select store_location,transaction_time,count(transaction_id) as th,
dense_rank() over(partition by store_location order by count(transaction_id) desc)
as dr from coffee_roasters group by 1,2)
select * from cte where dr in (1);

#22 wasq that return store-wise peak revenue hour using dense_rank()
with cte as
(select store_location,transaction_time,sum(revenue) as r,
dense_rank() over(partition by store_location order by sum(revenue) desc)
as dr from coffee_roasters group by 1,2)
select * from cte where dr in (1);

#23 wasq that return revenue contribution percentage of each store
select store_location,sum(revenue) as revenue,
round(percent_rank() over(order by sum(revenue) asc),2)
as per_rank
from coffee_roasters
group by 1;

#24 wasq that return rank of stores based on total revenue using rank()
select store_location,sum(revenue) as tr, rank()
over(order by sum(revenue) asc) as rank_f
from coffee_roasters group by 1;

#25 wasq that return top 3 revenue generating products 
#in each store using window function
with cte as
(select store_location,product_detail,sum(revenue) as r,
dense_rank() over(partition by store_location
order by sum(revenue) desc) as d_rn
from coffee_roasters
group by store_location, product_detail)
select *
from cte
where d_rn <= 3;

#26 wasq that return running total revenue by hour using window function
with cte as
(select transaction_time,sum(revenue) as tr
from coffee_roasters group by 1)
select transaction_time,tr,sum(tr) 
over(order by transaction_time)as running_total
from cte;

#27 wasq that return cumulative transaction count by hour
select transaction_time,count(transaction_id) as tc,sum(count(transaction_id))
over(order by transaction_Time) as cumulative_transaction_Count
from coffee_roasters group by 1;

#28 wasq that return most popular product category in each store
with cte as
(select store_location,product_Category,count(transaction_qty) as tq,
dense_rank() over(partition by store_location order by count(transaction_qty) desc)
as d_Rn from coffee_roasters group by 1,2)
select * from cte where d_Rn=1;

#29 wasq that return average revenue per transaction for each store
select store_location,round(avg(revenue),3) as avgr
from coffee_roasters group by 1;

#30 wasq that return busiest time bucket for each store using dense_rank()
with cte as
(select store_location,time_bucket,count(transaction_id) as ti,
dense_rank() over(partition by store_location order by count(transaction_id) desc)
as d_Rn from coffee_roasters group by 1,2)
select * from cte where d_rn =1;

